stages:
  - sonar
  - build
  - deploy
  - production



sonarscan:
  extends: .sonarscan
  image: reg.addinn-group.com/library/sonar-dotnet:6.0
  variables:
    FOLDER: ./src/Api
    CSPROJ_FILE: 'Api.csproj'


build:
  extends: .build_docker
  tags:
    - abridia


build-init:
  extends: .build_docker
  stage: build
  variables:
    CONTAINER_IMAGE: ${REGISTRY}/addinn/${CI_PROJECT_PATH_SLUG}-init
    DOCKERFILE: Dockerfile-init
  tags:
    - abridia



k8s-deploy:develop:
  extends: .deploy
  variables:
     HELM_OPTS: "--set ingress.host=plan-mercure.${DEVELOP_DOMAIN} --set initContainers[0].name=init-database --set initContainers[0].image=${CONTAINER_IMAGE}-init:${HELM_IMAGE_TAG}"
  tags:
    - abridia-dev




include:
  - project: 'library/stages'
    ref: master
    file: 'gitlab/sonar/sonarscan_hidden_dotnet.yaml'
  - project: 'library/stages'
    ref: master
    file: 'gitlab/migration/migration_hidden.yaml'
  - project: 'library/stages'
    ref: master
    file: 'gitlab/helm/deploy_hidden.yaml'
  - project: 'library/stages'
    ref: master
    file: 'gitlab/docker/build_hidden.yaml'
  - project: 'library/stages'
    ref: master
    file: 'gitlab/helm/production_hidden2.yaml'

  - project: 'library/stages'
    ref: master
    file: 'gitlab/helm/staging_hidden.yaml'
  - project: 'library/stages'
    ref: master
    file: '/gitlab/footer.yaml'
